### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [chadmmiles/project11#1]
It looks like the final criterion isn't yet complete:

> NOT display any links to unauthorized actions to anonymous visitors (such as links to create a new record, edit a record, or delete a record)

Even when not logged in, I see these links. Can you update this please?

**Comment by chadmmiles** [comment]
I've updated this, but will push it to my heroku app once I update my project 11 as well since I have them on the same app and want to keep the updated version live.

**Comment by chadmmiles** [comment]
Oops meant to post this on project 10. In the mean time, shouldn't the code "before_action :only_allow_signed_in_users, except: [:index, :show]" at the top of my listings controller make it so that only "show" will be seen? Not "destroy" and "edit". I thought that was what the except clause at the end did.

**Comment by chadmmiles** [comment]
All set now!

**Comment by chrisvfritz** [comment]
:+1: Looks good.
